/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_gaussianblur_BlurNative */

#ifndef _Included_com_android_gaussianblur_BlurNative
#define _Included_com_android_gaussianblur_BlurNative
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_android_gaussianblur_BlurNative
 * Method:    recursiveBlurBitmap
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_android_gaussianblur_BlurNative_recursiveBlurBitmap
        (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_android_gaussianblur_BlurNative
 * Method:    gaussBlurBitmap
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_android_gaussianblur_BlurNative_gaussBlurBitmap
        (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
